//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagInfoControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagInfoControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DeleteFolderHS {
            get {
                object obj = ResourceManager.GetObject("DeleteFolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FullScreenHS {
            get {
                object obj = ResourceManager.GetObject("FullScreenHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Abkhazian [abk];Achinese [ace];Acoli [ach];Adangme [ada];Adygei [ady];Afar [aar];Afrihili [afh];Afrikaans [afr];Afro-Asiatic (Other) [afa];Ainu [ain];Akan [aka];Akkadian [akk];Albanian [alb];Aleut [ale];Algonquian languages [alg];Altaic (Other) [tut];Amharic [amh];Angika [anp];Apache languages [apa];Arabic [ara];Aragonese [arg];Aramaic [arc];Arapaho [arp];Arawak [arw];Armenian [arm];Artificial (Other) [art];Assamese [asm];Asturian,Bable [ast];Athapascan languages [ath];Australian languages [aus];Austronesi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsoLanguages {
            get {
                return ResourceManager.GetString("IsoLanguages", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LeftArrowHS {
            get {
                object obj = ResourceManager.GetObject("LeftArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewDocumentHS {
            get {
                object obj = ResourceManager.GetObject("NewDocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Afrikaans [af];Arabic (U.A.E.) [ar-ae];Arabic (Bahrain) [ar-bh];Arabic (Algeria) [ar-dz];Arabic (Egypt) [ar-eg];Arabic (Iraq) [ar-iq];Arabic (Jordan) [ar-jo];Arabic (Kuwait) [ar-kw];Arabic (Lebanon) [ar-lb];Arabic (Libya) [ar-ly];Arabic (Morocco) [ar-ma];Arabic (Oman) [ar-om];Arabic (Qatar) [ar-qa];Arabic (Saudi Arabia) [ar-sa];Arabic (Syria) [ar-sy];Arabic (Tunisia) [ar-tn];Arabic (Yemen) [ar-ye];Arabic [ar];Assamese [as];Azeri [az];Belarusian [be];Bulgarian [bg];Bengali [bn];Catalan [ca];Czech [cs];Danis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RFC1766 {
            get {
                return ResourceManager.GetString("RFC1766", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RightArrowHS {
            get {
                object obj = ResourceManager.GetObject("RightArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightToLeftDoucmentHS {
            get {
                object obj = ResourceManager.GetObject("RightToLeftDoucmentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightToLeftDoucmentHS1 {
            get {
                object obj = ResourceManager.GetObject("RightToLeftDoucmentHS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WarningHS {
            get {
                object obj = ResourceManager.GetObject("WarningHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
